### ISSUE TITLE
Add Mac OS X specific use instructions

### ISSUE THREAD

**Issue by truedat101** [carblue/sodium#3]
OS X adds a few extra steps (I think) as far as using this module.  Because precompiled binaries are not included for libsodium, one will need to build libsodium 1.0.16 and provide the library on the path.  I'll attempt to get that documented here.  I don't think there are any additional changes needed to the dub json file, but I've noticed a few other projects out there that do support OS X out of the box, so I'll take a look to see if there is some best practice that can be incorporated.   LD_LIBRARY_PATH  is apparently no longer a thing (I'm confused about that and why that changed) so will make a recommendation here.

**Comment by truedat101** [comment]
Here's the recommendation:

- On OS X, as long as the user has (1) built libsodium1.0.16 and (2) performed a default install, under /usr/local then (3) sodium deimos will find it under /usr/local.

That seems somewhat duh, obvious, however, efforts to get my parent project dependent on sodium to look elsewhere, for example, in libs dir in my project, using -lflags-osx-x86_64, for example, were ignored.  I do not know if this is ldc2 and dyld or something else in the sodium deimos bindings making the assumption that we must look only under /usr/local.  Was getting this error: dyld: Library not loaded: /usr/local/lib/libsodium.23.dylib

**Comment by truedat101** [comment]
Personally, I don't like that I couldn't use the lflags to influence where the OS X linker looks.  And I don't like that we can no longer rely on LD_LIBRARY_PATH.  Leave it and hopefully someone who understands better can optimize the recommendation to allow loading of the library from somewhere else.

**Comment by carblue** [comment]
Thank You for Your notice about Mac OS X specifics and sorry for replying late:  
I don't have Mac OS X available nor much knowledge of that (but Linux and Windows), thus I depend on recommendations like Yours.

LD_LIBRARY_PATH: I never liked the idea of LD_LIBRARY_PATH (except as last resort).  
As with any other binding, also this one expects the library binary (to link against)  
1) being available on the system,
2) the OS's linker and loader will find the library at known (configurable) standard locations at compile/link time **and** load/runtime time, or
3) the user adapts dub.json to specify user-specific library information (name and location), see below in the end.

e.g. for Linux/Ubuntu Bionic there is a package 'libsodium23' that provides a linkname 'libsodium.so.23' pointing to the actual binary provided (libsodium.so.23.1.0 <=> sodium version v1.0.16), as well as a package 'libsodium-dev' that i.a. adds a linkname 'libsodium.so', pointing to the same libsodium.so.23.1.0.
Both linknames installed by the packages are located within linker's and loader's standard search path (x86_64 on Ubuntu: /usr/lib/x86_64-linux-gnu). Similar rules apply for Windows, where .dll are searched along %PATH.
For Linux, /usr/local/lib is one of a couple of configured standard search locations as well (see /etc/ld.so.conf.d).

Your statement "we must look only under /usr/local" is not quite correct: It's not "ldc2 and dyld or something else in the sodium deimos bindings" making assumptions, but You Yourself decided that /usr/local/lib is the location to look at for the libsodium binary when performing a default install (I assume 'default' refers to following the instruction on https://download.libsodium.org/doc/installation "Compilation on Unix-like systems").
I recommend to always first run ./configure --help  in order to see Your options (--libdir, EPREFIX or PREFIX are Your friends here).

It's also not correct that Your flags "using -lflags-osx-x86_64, for example, were ignored": It just wasn't complete, You declared where to look for the library while compiling and linking, BUT not where to look while loading/running the executable (You got an error from the loader, but not from compiler/linker (if I understood the OSX messages correctly!): Assuming this works in the same way for Linux/OSX, You have to specify -rpath=/somePath as well if Yo want to deviate from the standard library search locations.

With the Mac OS X related infos extracted from Your comments, with my new release I updated both deimos/dub.json and wrapper/dub.json, the relevant part excerpted (everything except "versions" and "libs" are disregarded comments only):
```
	"version_identifiers_possible_one_of": ["bin_v1_0_18 or bin_v1_0_17 or bin_v1_0_16"],
	"versions": ["bin_v1_0_18"],
	"libs": ["sodium"],

	"alternative_libname_if_no_dev_package_installed:_libs-linux": [":libsodium.so.23"],
	"alternative_libname_if_no_dev_package_installed:_libs-osx": [":libsodium.23.dylib"],
	"alternative_nonstandard_liblocation:_lflags-posix": [
		"     -L/path/to/some/dir",
		"-rpath=/path/to/some/dir"
	],
```

I recommend to install libsodium also on Mac OS X to a standard location known to linker and loader.
If You insist on deviating, then use:
```
	"lflags-osx-x86_64": [
		"     -L/path/to/some/dir",
		"-rpath=/path/to/some/dir"
	],
```

The reason to possibly use "alternative_libname_if_no_dev_package_installed": Technically it's not required to install a dev-package just to get the linkname libsodium.dylib or libsodium.so.
What a library package provides is sufficient, but we then must be more specific about the library's name, including soname information (which may change and is not optimal for a generic dub.json).

I hope, the binding works for OSX now out of the box as well.
PS: Read about bin_v1_0_18 etc. on https://github.com/carblue/sodium

**Comment by truedat101** [comment]
Thanks for the detailed reply.  I will give this a shot on my OS X device.

One of the challenges with the OS X environment is that we have 3-4 places where things are typically installed, depending on the type of software and how it is being built.  Typical open source goes into /usr/local, as with linux, but most users end up installing popular projects via Brew or MacPorts or fink or similar.  So those things go into some other special locations.

**Comment by truedat101** [comment]
And thanks for the work on this.

**Comment by truedat101** [comment]
So one thing to keep an eye on, libsodium hasn't been updated since 2019.  Not sure what's up with that.  I haven't been tracking development.
